/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface CodeFile {
  name: string;
  path: string;
  language: string;
  content: string;
  description: string;
}

export const CSHARP_CODE_FILES: CodeFile[] = [
  {
    name: "Models.cs",
    path: "VektorOps.Contracts/Models.cs",
    language: "csharp",
    description: "Strongly typed immutable records holding diagnostic telemetry, manufacturer contracts, and grounding payloads.",
    content: `using System;

namespace VektorOps.Contracts
{
    /// <summary>
    /// Represents an immutable hardware-level telemetry log generated by physical CPU/FPGA nodes.
    /// </summary>
    public record HardwareAlertLog(
        string DeviceId,
        string NodeTenantId,
        string RegisterErrorCode,
        string HexDumpValue,
        DateTime TelemetryTimestamp
    );

    /// <summary>
    /// Represents a manufacturer agreements model detailing service expectations.
    /// </summary>
    public record WarrantySlaContract(
        string ManufacturerId,
        string AssetSerialRange,
        DateTime ExpirationDate,
        int ResponseTimeThresholdHours
    );

    /// <summary>
    /// The final consolidated payload merging diagnostics telemetry, technical metadata, and compliance checks.
    /// </summary>
    public record DiagnosticsPayload(
        HardwareAlertLog TelemetryLog,
        RegisterMetadata MatchedRegister,
        WarrantySlaContract SlaInfo,
        string VendorComplianceStatus,
        double ProcessingMicroseconds
    );

    /// <summary>
    /// Bit-level register metadata harvested via semantic lookup.
    /// </summary>
    public record RegisterMetadata(
        string ErrorCode,
        string RegisterName,
        int FailingBit,
        string Description,
        string HardwareSubsystem,
        string RecommendedMitigation
    );
}`
  },
  {
    name: "SecurityBoundaryViolationException.cs",
    path: "VektorOps.Exceptions/SecurityBoundaryViolationException.cs",
    language: "csharp",
    description: "Domain-specific exception enforcing robust corporate boundaries and blocking unauthorized multi-tenant queries.",
    content: `using System;

namespace VektorOps.Exceptions
{
    /// <summary>
    /// Exception thrown when telemetry data is parsed under a tenant context that disagrees with the telemetry source tenant.
    /// </summary>
    public class SecurityBoundaryViolationException : Exception
    {
        public string ActiveTenant { get; }
        public string LogTenant { get; }
        public string DeviceId { get; }

        public SecurityBoundaryViolationException(string activeTenant, string logTenant, string deviceId)
            : base($"CRITICAL SEGREGATION BREACH: Tenant token validation failed. Active session context is '{activeTenant}' but telemetry log originated from device '{deviceId}' under tenant '{logTenant}'. Access denied.")
        {
            ActiveTenant = activeTenant;
            LogTenant = logTenant;
            DeviceId = deviceId;
        }
    }
}`
  },
  {
    name: "FoundryIqGroundingService.cs",
    path: "VektorOps.Services/FoundryIqGroundingService.cs",
    language: "csharp",
    description: "Foundry IQ Grounding repository loaded with core register specifications and SLA thresholds.",
    content: `using System;
using System.Collections.Generic;
using System.Linq;
using VektorOps.Contracts;

namespace VektorOps.Services
{
    public interface IFoundryIqGroundingService
    {
        RegisterMetadata QueryRegisterSpecifications(string registerErrorCode);
        WarrantySlaContract ResolveWarrantyContract(string manufacturerId, string deviceId);
    }

    /// <summary>
    /// A high-performance local grounding repository implementing simulated semantic mapping.
    /// </summary>
    public class FoundryIqGroundingService : IFoundryIqGroundingService
    {
        // Seeds architectural datasheets as an efficient compiled memory lookup
        private readonly Dictionary<string, RegisterMetadata> _registerRegistry = new()
        {
            {
                "0xERR_77B",
                new RegisterMetadata(
                    "0xERR_77B",
                    "CPU_L2_CACHE_PARITY_CTRL",
                    14,
                    "L2 Tag RAM parity error detected on index 2198. Possible high cosmic-ray interference or silicon thermal throttling.",
                    "SRAM Cache Controller",
                    "Assert register 0x41C to reset L2 sector, scale down memory bus frequency by 50MHz, and re-evaluate ECC counters."
                )
            },
            {
                "0xERR_A4F",
                new RegisterMetadata(
                    "0xERR_A4F",
                    "DRAM_MEM_VOLT_SENSE",
                    2,
                    "Memory channel B core voltage (VDDQ) dropped below critical threshold (1.12V vs 1.20V expected). High susceptibility to bit flip errors.",
                    "Memory Subsystem",
                    "Request microcode calibration check. Disptach a power rail feedback event to the BIOS PMIC driver wrapper."
                )
            },
            {
                "0xERR_F8C",
                new RegisterMetadata(
                    "0xERR_F8C",
                    "PCIE_BUS_FRAM_COLLISION",
                    9,
                    "PCIe Gen5 physical block lane synchronizer loss-of-signal. Frame misalignment rate exceeded 15% on Link Port 4.",
                    "PCIe Root Complex",
                    "Trigger logical retrain sequence in port register 0xDE02. If retries expire, fall back link lanes from x16 to x8 width."
                )
            }
        };

        private readonly List<WarrantySlaContract> _activeContracts = new()
        {
            new WarrantySlaContract("INTEL_FOUNDRY_CORP", "SN-INTEL-000000", DateTime.UtcNow.AddDays(730), 4),
            new WarrantySlaContract("AMD_SEMI_GLOBAL", "SN-AMD-999999", DateTime.UtcNow.AddDays(365), 12),
            new WarrantySlaContract("TSMC_FAB_NET", "SN-TSMC-500500", DateTime.UtcNow.AddDays(180), 2)
        };

        public RegisterMetadata QueryRegisterSpecifications(string registerErrorCode)
        {
            if (_registerRegistry.TryGetValue(registerErrorCode, out var metadata))
            {
                return metadata;
            }

            // Fallback for custom or undocumented error registers
            return new RegisterMetadata(
                registerErrorCode,
                "VENDOR_UNDOC_REGISTER",
                0,
                $"Unstructured register dump matching general diagnostics offset. Raw hex flags detected.",
                "General Compute Complex",
                "Execute fallback CMOS firmware level-1 scan and query physical line technician index."
            );
        }

        public WarrantySlaContract ResolveWarrantyContract(string manufacturerId, string deviceId)
        {
            // Resolves the warranty contract based on matching manufacturer ID
            var contract = _activeContracts.FirstOrDefault(c => c.ManufacturerId == manufacturerId);
            if (contract != null)
            {
                return contract;
            }

            // Return generic standard warranty SLA
            return new WarrantySlaContract(
                manufacturerId ?? "GENERIC_VENDOR",
                deviceId,
                DateTime.UtcNow.AddDays(90),
                24
            );
        }
    }
}`
  },
  {
    name: "McpInterface.cs",
    path: "VektorOps.Services/McpInterface.cs",
    language: "csharp",
    description: "Secure gateway acting as the Model Context Protocol (MCP) interface, enforcing strict security boundary guardrails.",
    content: `using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using VektorOps.Contracts;
using VektorOps.Exceptions;

namespace VektorOps.Services
{
    /// <summary>
    /// Gateway interfacing the Custom Engine Agent with simulated Copilot lifecycle endpoints.
    /// </summary>
    public class McpInterface
    {
        private readonly ConcurrentQueue<DiagnosticsPayload> _incidentLifecycleQueue = new();
        private readonly IFoundryIqGroundingService _groundingService;

        public McpInterface(IFoundryIqGroundingService groundingService)
        {
            _groundingService = groundingService ?? throw new ArgumentNullException(nameof(groundingService));
        }

        /// <summary>
        /// Ingests a raw hardware telemetric log, validates tenant token alignment, and decorates payload.
        /// </summary>
        /// <param name="telemetryLog">The telemetry node input byte package</param>
        /// <param name="activeSessionTenantToken">The security context of the active tenant querying the node</param>
        public DiagnosticsPayload ProcessAndRegisterIncident(HardwareAlertLog telemetryLog, string activeSessionTenantToken)
        {
            // Business Guardrail: Tenant Separation Enforcement
            if (telemetryLog.NodeTenantId != activeSessionTenantToken)
            {
                throw new SecurityBoundaryViolationException(activeSessionTenantToken, telemetryLog.NodeTenantId, telemetryLog.DeviceId);
            }

            var startTime = DateTime.UtcNow;

            // 1. Semantic register map lookup in metadata registry
            var registerMeta = _groundingService.QueryRegisterSpecifications(telemetryLog.RegisterErrorCode);

            // 2. Resolve SLA obligations
            string manufacturerId = DetermineManufacturerFromDevice(telemetryLog.DeviceId);
            var contractSla = _groundingService.ResolveWarrantyContract(manufacturerId, telemetryLog.DeviceId);

            // 3. Evaluate operational compliance status
            string compliance = DetermineComplianceStatus(contractSla);

            var endTime = DateTime.UtcNow;
            double elapsedMicroseconds = (endTime - startTime).TotalMilliseconds * 1000.0;

            var payload = new DiagnosticsPayload(
                telemetryLog,
                registerMeta,
                contractSla,
                compliance,
                elapsedMicroseconds
            );

            // Append incident package to secure MCP queue
            _incidentLifecycleQueue.Enqueue(payload);

            return payload;
        }

        public IEnumerable<DiagnosticsPayload> GetQueuedIncidents()
        {
            return _incidentLifecycleQueue.ToArray();
        }

        private string DetermineManufacturerFromDevice(string deviceId)
        {
            if (deviceId.StartsWith("CPU-INTEL")) return "INTEL_FOUNDRY_CORP";
            if (deviceId.StartsWith("GPU-AMD")) return "AMD_SEMI_GLOBAL";
            return "TSMC_FAB_NET";
        }

        private string DetermineComplianceStatus(WarrantySlaContract contract)
        {
            if (contract.ExpirationDate < DateTime.UtcNow)
            {
                return "OUT_OF_WARRANTY_COMPLIANCE"; // Breach state
            }
            if (contract.ResponseTimeThresholdHours <= 4)
            {
                return "CRITICAL_CLASS_GOLD_SLA"; // Platinum level
            }
            return "STANDARD_OPERATIONAL_SLA";
        }
    }
}`
  },
  {
    name: "AdaptiveCardEngine.cs",
    path: "VektorOps.Engine/AdaptiveCardEngine.cs",
    language: "csharp",
    description: "Presentation module converting processed payload records into highly scannable Copilot Adaptive Cards.",
    content: `using System;
using System.Text.Json;
using VektorOps.Contracts;

namespace VektorOps.Engine
{
    /// <summary>
    /// Translates diagnostic telemetry payloads into dense, actionable Microsoft 365 Copilot Adaptive Card layouts.
    /// </summary>
    public static class AdaptiveCardEngine
    {
        public static string GenerateCopilotCardJson(DiagnosticsPayload payload)
        {
            var headerColor = payload.VendorComplianceStatus == "OUT_OF_WARRANTY_COMPLIANCE" ? "Attention" : "Warning";
            var textStatus = payload.VendorComplianceStatus.Replace("_", " ");

            var cardStructure = new
            {
                type = "AdaptiveCard",
                version = "1.5",
                body = new object[]
                {
                    new {
                        type = "Container",
                        style = "emphasis",
                        bleed = true,
                        items = new object[]
                        {
                            new {
                                type = "TextBlock",
                                text = $"VEKTOROPS TELEMETRY ALERT: {payload.TelemetryLog.RegisterErrorCode}",
                                size = "Medium",
                                weight = "Bolder",
                                color = headerColor
                            },
                            new {
                                type = "TextBlock",
                                text = $"DEVICE: {payload.TelemetryLog.DeviceId} | TENANT: {payload.TelemetryLog.NodeTenantId}",
                                isSubtle = true,
                                size = "Small",
                                spacing = "None"
                            }
                        }
                    },
                    new {
                        type = "Container",
                        spacing = "Medium",
                        items = new object[]
                        {
                            new {
                                type = "TextBlock",
                                text = "Foundry IQ Register Diagnosis",
                                weight = "Bolder",
                                size = "Default"
                            },
                            new {
                                type = "FactSet",
                                facts = new object[]
                                {
                                    new { title = "Mapped Register", value = payload.MatchedRegister.RegisterName },
                                    new { title = "Failing Bit Index", value = $"Bit {payload.MatchedRegister.FailingBit} of 32" },
                                    new { title = "Description", value = payload.MatchedRegister.Description },
                                    new { title = "Silicon Domain", value = payload.MatchedRegister.HardwareSubsystem }
                                }
                            }
                        }
                    },
                    new {
                        type = "Container",
                        spacing = "Medium",
                        style = "accent",
                        items = new object[]
                        {
                            new {
                                type = "TextBlock",
                                text = "Compliance & Lifecycle Bounds",
                                weight = "Bolder"
                            },
                            new {
                                type = "TextBlock",
                                text = $"Log Timestamp: {payload.TelemetryLog.TelemetryTimestamp:yyyy-MM-dd HH:mm:ss.fff} UTC",
                                size = "Small",
                                isSubtle = true
                            },
                            new {
                                type = "FactSet",
                                facts = new object[]
                                {
                                    new { title = "SLA Target Limit", value = $"{payload.SlaInfo.ResponseTimeThresholdHours} Hours (Max Response)" },
                                    new { title = "Contract Expiration", value = payload.SlaInfo.ExpirationDate.ToString("yyyy-MM-dd") },
                                    new { title = "Mitigation Path", value = payload.MatchedRegister.RecommendedMitigation },
                                    new { title = "System Compliance", value = textStatus }
                                }
                            }
                        }
                    }
                },
                actions = new object[]
                {
                    new {
                        type = "Action.Submit",
                        title = "Trigger Parts Dispatch",
                        data = new
                        {
                            action = "dispatch_parts",
                            deviceId = payload.TelemetryLog.DeviceId,
                            errorCode = payload.TelemetryLog.RegisterErrorCode,
                            mitigation = payload.MatchedRegister.RecommendedMitigation
                        }
                    },
                    new {
                        type = "Action.OpenUrl",
                        title = "Review Silicon Datasheet",
                        url = $"https://vektorops.enterprise.internal/specifications/{payload.MatchedRegister.RegisterName}"
                    }
                }
            };

            return JsonSerializer.Serialize(cardStructure, new JsonSerializerOptions { WriteIndented = true });
        }
    }
}`
  },
  {
    name: "Program.cs",
    path: "Program.cs",
    language: "csharp",
    description: "The primary high-performance execution loop seeding standard identities and streaming live diagnostic packages.",
    content: `using System;
using System.Threading;
using System.Threading.Tasks;
using VektorOps.Contracts;
using VektorOps.Engine;
using VektorOps.Exceptions;
using VektorOps.Services;

namespace VektorOps
{
    public class Program
    {
        public static async Task Main(string[] args)
        {
            Console.WriteLine("==========================================================================");
            Console.WriteLine("  VektorOps (CEA) - HIGH-PERFORMANCE MULTI-TENANT DIAGNOSTICS & COMPLIANCE");
            Console.WriteLine("  Starting diagnostic stream pipeline and telemetry monitoring node...");
            Console.WriteLine("==========================================================================\\n");

            // 1. Initialize core system modules
            IFoundryIqGroundingService groundingService = new FoundryIqGroundingService();
            McpInterface mcpInstance = new McpInterface(groundingService);

            // Active boundary context token matching user query credentials
            string userSessionToken = "TENANT-ALPHA";
            Console.WriteLine($"[SYSTEM SETUP] Active session context locked to Tenant ID: '{userSessionToken}'");

            // 2. Generate a stream of architectural diagnostics events
            HardwareAlertLog[] eventDumps = new[]
            {
                new HardwareAlertLog(
                    "CPU-INTEL-99X-A", 
                    "TENANT-ALPHA", 
                    "0xERR_77B", 
                    "0x000F411082BF90D3", 
                    DateTime.UtcNow
                ),
                new HardwareAlertLog(
                    "GPU-AMD-RYZ88", 
                    "TENANT-ALPHA", 
                    "0xERR_A4F", 
                    "0xFFFFFFFFD904B4C0", 
                    DateTime.UtcNow.AddSeconds(-5)
                ),
                new HardwareAlertLog(
                    "NODE-ROUTER-P8", 
                    "TENANT-BETA",   // Mismatched tenant payload to trigger strict guardrail constraint
                    "0xERR_F8C", 
                    "0xABCD7739FFFF2290", 
                    DateTime.UtcNow.AddSeconds(-2)
                )
            };

            // 3. Streaming telemetry parsing cycle
            for (int i = 0; i < eventDumps.Length; i++)
            {
                var inputLog = eventDumps[i];
                Console.WriteLine($"\\n[TELEMETRY INGESTED] Ingestion cycle {i + 1} of {eventDumps.Length}");
                Console.WriteLine($"  Device: {inputLog.DeviceId} | Origin: {inputLog.NodeTenantId} | Error: {inputLog.RegisterErrorCode}");

                try
                {
                    // Call the secure boundary validator gateway
                    DiagnosticsPayload payload = mcpInstance.ProcessAndRegisterIncident(inputLog, userSessionToken);
                    
                    Console.WriteLine($"[GROUNDING TRACE] Semantic resolution match: {payload.MatchedRegister.RegisterName}");
                    Console.WriteLine($"  Active Silicon Domain: {payload.MatchedRegister.HardwareSubsystem}");
                    Console.WriteLine($"  Resolved SLA Threshold: {payload.SlaInfo.ResponseTimeThresholdHours} Hours ({payload.VendorComplianceStatus})");
                    Console.WriteLine($"  Engine Parsing Duration: {payload.ProcessingMicroseconds:F2} microseconds.");

                    // Convert payload using adaptive cards presentation module
                    Console.WriteLine("[CARD RENDER] Generating Microsoft 365 Copilot Adaptive Card...");
                    string cardJson = AdaptiveCardEngine.GenerateCopilotCardJson(payload);
                    Console.WriteLine($"\\n{cardJson}\\n");
                    Console.WriteLine("--------------------------------------------------------------------------");
                }
                catch (SecurityBoundaryViolationException ex)
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine($"[GUARDRAIL CRITICAL EXCEPTION] {ex.Message}");
                    Console.WriteLine($"  Boundary Event successfully mitigated. Telemetry payload rejected to deny multi-tenant leakage.");
                    Console.ResetColor();
                    Console.WriteLine("--------------------------------------------------------------------------");
                }
                
                // Simulate telemetry line stream frequency delays
                await Task.Delay(400);
            }

            Console.WriteLine("\\n==========================================================================");
            Console.WriteLine("  DIAGNOSTICS SEQUENCE SUSPENDED. All secure boundaries verified successfully.");
            Console.WriteLine("==========================================================================");
        }
    }
}`
  }
];
